version: '3.7'
services:
  db:
    container_name: pg_container
    image: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pg_admin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '8081:80'
